### ISSUE TITLE
pinned posts are sent continuously

### ISSUE THREAD

**Issue by abm82** [rehmanali007/instagram-to-telegram#4]
I had to enter feedWaitTime=0 in conf.ini for it to work, but it sends all the posts that are pinned repeatedly, without stopping

**Comment by runetech0** [comment]
Hey, sorry to say but I haven't been maintaining this repository anymore so it's better to get some updated version of the bot that uses newer version of APIs of discord and telegram.
Thanks for taking time to try it out anyhow!
